const mongoose = require('mongoose');

const employeeSchema = new mongoose.Schema({
  deviceUserId: { type: String, required: true, unique: true },
  name: { type: String, required: true },
  phone: { type: String },
  alternatePhone: { type: String },
  department: { type: String },
  role: { type: String, enum: ['Employee', 'Manager', 'Board Member'], default: 'Employee' },
  employeeCode: { type: String },
  joiningDate: { type: String },
  dateOfBirth: { type: String },
  gender: { type: String },
  employmentType: { type: String },
  alias: { type: String },
  workEmail: { type: String },
  personalEmail: { type: String },
  pan: { type: String },
  maritalStatus: { type: String },
  bloodGroup: { type: String },
  fatherName: { type: String },
  motherName: { type: String },
  bankAccount: { type: String },
  ifsc: { type: String },
  accountType: { type: String },
  bankName: { type: String },
  bankBranch: { type: String },
  accountHolder: { type: String },
  aadhaar: { type: String },
  emergencyPhone: { type: String },
  nationality: { type: String },
  designation: { type: String },
  location: { type: String },
  team: { type: String },
  shift: { type: String },
  monthlySalary: { type: Number, min: 0, default: 0 },
  salaryEffectiveFrom: { type: String },
  salaryNotes: { type: String },
  active: { type: Boolean, default: true },
}, { timestamps: true });

module.exports = mongoose.model('Employee', employeeSchema);
